version: "2.4"

services:
  freeform:
    # build time
    image: freeform
    container_name: freeform
    build:
      context: .
    
    # run time
    runtime: nvidia # {nvidia | runc}
    shm_size: 4gb
    ports:
      - "50051:50051"
    volumes: 
      - /home/ubuntu/share/freeform:/app/data