version: "2.4"

services:
  freeform:
    # build time
    image: freeform
    container_name: freeform
    build:
      context: .
    
    # run time
    runtime: nvidia # {nvidia | runc}
    shm_size: 4gb
    environment: 
      - CUDA_VISIBLE_DEVICE=1,3
      - GPU_ID=cuda:0
    ports:
      - "50051:50051"
    volumes: 
      - /home/ubuntu/share/freeform:/app/data
    # networks: [core]